// Mapa nazwa drużyny -> emoji flagi.
// Nazwy po angielsku, jak zwraca football API. Zawiera warianty nazw.
const FLAGS = {
  // Gospodarze i Ameryki
  'USA': '🇺🇸', 'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Argentina': '🇦🇷',
  'Brazil': '🇧🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Ecuador': '🇪🇨',
  'Paraguay': '🇵🇾',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Venezuela': '🇻🇪',
  'Bolivia': '🇧🇴',
  'Panama': '🇵🇦',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Haiti': '🇭🇹',
  'Curacao': '🇨🇼', 'Curaçao': '🇨🇼',

  // Europa
  'Spain': '🇪🇸',
  'France': '🇫🇷',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Northern Ireland': '🇬🇧',
  'Ireland': '🇮🇪', 'Republic of Ireland': '🇮🇪',
  'Portugal': '🇵🇹',
  'Germany': '🇩🇪',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Italy': '🇮🇹',
  'Croatia': '🇭🇷',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Denmark': '🇩🇰',
  'Norway': '🇳🇴',
  'Sweden': '🇸🇪',
  'Poland': '🇵🇱',
  'Ukraine': '🇺🇦',
  'Czech Republic': '🇨🇿', 'Czechia': '🇨🇿',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Serbia': '🇷🇸',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Greece': '🇬🇷',
  'Turkey': '🇹🇷', 'Türkiye': '🇹🇷',
  'Albania': '🇦🇱',
  'Georgia': '🇬🇪',
  'Finland': '🇫🇮',
  'Iceland': '🇮🇸',
  'North Macedonia': '🇲🇰',
  'Bosnia and Herzegovina': '🇧🇦', 'Bosnia-Herzegovina': '🇧🇦',
  'Kosovo': '🇽🇰',

  // Afryka
  'Morocco': '🇲🇦',
  'Senegal': '🇸🇳',
  'Tunisia': '🇹🇳',
  'Algeria': '🇩🇿',
  'Egypt': '🇪🇬',
  'Nigeria': '🇳🇬',
  'Ghana': '🇬🇭',
  'Cameroon': '🇨🇲',
  'Ivory Coast': '🇨🇮', "Cote d'Ivoire": '🇨🇮', "Côte d'Ivoire": '🇨🇮',
  'South Africa': '🇿🇦',
  'Cape Verde Islands': '🇨🇻', 'Cape Verde': '🇨🇻', 'Cabo Verde': '🇨🇻',
  'Mali': '🇲🇱',
  'Burkina Faso': '🇧🇫',
  'DR Congo': '🇨🇩', 'Congo DR': '🇨🇩',
  'Gabon': '🇬🇦',
  'Zambia': '🇿🇲',
  'Benin': '🇧🇯',
  'Guinea': '🇬🇳',
  'Uganda': '🇺🇬',
  'Equatorial Guinea': '🇬🇶',
  'Madagascar': '🇲🇬',
  'Mozambique': '🇲🇿',
  'Angola': '🇦🇴',
  'Libya': '🇱🇾',

  // Azja i Oceania
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷', 'Korea Republic': '🇰🇷',
  'Iran': '🇮🇷', 'IR Iran': '🇮🇷',
  'Saudi Arabia': '🇸🇦',
  'Qatar': '🇶🇦',
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'Uzbekistan': '🇺🇿',
  'Jordan': '🇯🇴',
  'Iraq': '🇮🇶',
  'United Arab Emirates': '🇦🇪', 'UAE': '🇦🇪',
  'China': '🇨🇳', 'China PR': '🇨🇳',
  'Indonesia': '🇮🇩',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Oman': '🇴🇲',
  'Bahrain': '🇧🇭',
  'Kuwait': '🇰🇼',
  'Palestine': '🇵🇸',
  'Syria': '🇸🇾',
  'Lebanon': '🇱🇧',
  'India': '🇮🇳',
  'Kyrgyzstan': '🇰🇬',
  'Tajikistan': '🇹🇯',
  'North Korea': '🇰🇵', 'Korea DPR': '🇰🇵',
  'Malaysia': '🇲🇾',
  'Fiji': '🇫🇯',
  'New Caledonia': '🇳🇨',
  'Tahiti': '🇵🇫',
  'Papua New Guinea': '🇵🇬',
  'Solomon Islands': '🇸🇧',
  'Russia': '🇷🇺',
}

// Zwraca flagę dla drużyny: najpierw z bazy, potem ze słownika (dokładne dopasowanie
// lub bez rozróżniania wielkości liter), na końcu null.
export function flagFor(teamName, dbFlag) {
  if (dbFlag) return dbFlag
  if (!teamName) return null
  if (FLAGS[teamName]) return FLAGS[teamName]
  const lower = teamName.toLowerCase().trim()
  const hit = Object.keys(FLAGS).find(k => k.toLowerCase() === lower)
  return hit ? FLAGS[hit] : null
}

export default FLAGS
